# Generated by Django 2.2.8 on 2020-01-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0026_auto_20200126_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('shack', 'Snack'), ('dinner', 'Dinner')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_product_amount', to='meals.Meal')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_product_amount', to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='products',
            field=models.ManyToManyField(related_name='meal_products', through='meals.ProductAmount', to='products.Product', verbose_name='Products'),
        ),
    ]
