# Generated by Django 2.2.8 on 2020-03-11 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_productamount_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productamount',
            name='date',
        ),
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
