# Generated by Django 2.2.8 on 2020-02-03 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterdrinking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_drinking', to=settings.AUTH_USER_MODEL),
        ),
    ]
