# Generated by Django 2.2.8 on 2020-02-20 06:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='', verbose_name='Icon')),
                ('name', models.CharField(max_length=80, verbose_name='Activity name')),
                ('сonsumption', models.FloatField(validators=[django.core.validators.MinValueValidator(0.9)], verbose_name='Consumption')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(verbose_name='Minutes')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_time', to='activities.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_time', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ManyToManyField(through='activities.ActivityTime', to=settings.AUTH_USER_MODEL),
        ),
    ]
