# Generated by Django 2.2.8 on 2020-03-03 06:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, null=True, upload_to='activities', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'svg'])], verbose_name='Icon')),
                ('name', models.CharField(max_length=80, verbose_name='Activity name')),
                ('сonsumption', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumption')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Custom Activity name')),
                ('сonsumption', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomActivityTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_time', models.PositiveIntegerField(verbose_name='Custom Activity Time (Minutes)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_activity_time', to='activities.CustomUserActivity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(verbose_name='Activity Time (Minutes)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_time', to='activities.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_time', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='activities', through='activities.ActivityTime', to=settings.AUTH_USER_MODEL),
        ),
    ]
