# Generated by Django 2.2.8 on 2020-02-20 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ManyToManyField(related_name='activities', through='activities.ActivityTime', to=settings.AUTH_USER_MODEL),
        ),
    ]
