# Generated by Django 2.2.8 on 2020-02-20 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20200220_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='activities', through='activities.ActivityTime', to=settings.AUTH_USER_MODEL),
        ),
    ]
