# Generated by Django 2.2.8 on 2020-02-21 07:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0004_auto_20200220_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='сonsumption',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumption'),
        ),
        migrations.CreateModel(
            name='CustomUserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Custom Activity name')),
                ('сonsumption', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
