# Generated by Django 2.2.8 on 2020-02-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20200221_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuseractivity',
            name='activity_time_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Activity Time (Minutes)'),
        ),
        migrations.AlterField(
            model_name='activitytime',
            name='minutes',
            field=models.PositiveIntegerField(verbose_name='Activity Time (Minutes)'),
        ),
    ]
