# Generated by Django 2.2.8 on 2020-02-26 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20200221_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='activitytime',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_time', to='activities.Activity'),
        ),
        migrations.AlterField(
            model_name='activitytime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_time', to=settings.AUTH_USER_MODEL),
        ),
    ]
