# Generated by Django 2.2.8 on 2020-02-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20200226_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Icon'),
        ),
    ]
