# Generated by Django 2.2.8 on 2020-02-26 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20200226_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='activities', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'svg'])], verbose_name='Icon'),
        ),
    ]
