# Generated by Django 2.2.4 on 2019-08-20 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100, verbose_name='Kind')),
                ('start_time_millis', models.BigIntegerField(verbose_name='Start Time')),
                ('expiry_time_millis', models.BigIntegerField(verbose_name='Expiry Time')),
                ('auto_renewing', models.BooleanField(verbose_name='Auto Renewing')),
                ('price_currency_code', models.CharField(max_length=5, verbose_name='Price Currency Code')),
                ('price_amount_micros', models.BigIntegerField(verbose_name='Price Amount')),
                ('country_code', models.CharField(max_length=5, verbose_name='Country Code')),
                ('cancel_reason', models.IntegerField(verbose_name='Cancel Reason')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order ID')),
                ('acknowledgement_state', models.IntegerField(verbose_name='Cancel Reason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
