# Generated by Django 2.2.8 on 2020-02-16 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('users', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermittent_fasting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
