# Generated by Django 2.2.8 on 2020-02-16 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intermittent_fasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasting',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermittent_fasting', to=settings.AUTH_USER_MODEL),
        ),
    ]
