# Generated by Django 2.2.3 on 2019-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190703_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='portion',
            field=models.FloatField(default=100),
        ),
    ]
