# Generated by Django 2.2.3 on 2019-07-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_measurementunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementunit',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
