# Generated by Django 2.2.4 on 2019-08-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190730_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='measurementunit',
            options={'verbose_name': 'Measurement unit', 'verbose_name_plural': 'Measurement units'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='full_info',
            field=models.TextField(blank=True, verbose_name='Full info'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.Category', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_units', to='products.Product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.FloatField(default=-1.0, verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(default=-1.0, verbose_name='Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cellulose',
            field=models.FloatField(default=-1.0, verbose_name='Cellulose'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cholesterol',
            field=models.FloatField(default=-1.0, verbose_name='Cholesterol'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(default=-1.0, verbose_name='Fats'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_info',
            field=models.TextField(blank=True, verbose_name='Full info'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_liquid',
            field=models.BooleanField(verbose_name='Is liquid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kilojoules',
            field=models.FloatField(default=-1.0, verbose_name='Kilojoules'),
        ),
        migrations.AlterField(
            model_name='product',
            name='monosaturated_fats',
            field=models.FloatField(default=-1.0, verbose_name='Monosaturated fats'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='polysaturated_fats',
            field=models.FloatField(default=-1.0, verbose_name='Polysaturated fats'),
        ),
        migrations.AlterField(
            model_name='product',
            name='portion',
            field=models.FloatField(default=100, verbose_name='Portion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pottasium',
            field=models.FloatField(default=-1.0, verbose_name='Pottasium'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(default=-1.0, verbose_name='Proteins'),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fats',
            field=models.FloatField(default=-1.0, verbose_name='Saturated fats'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sodium',
            field=models.FloatField(default=-1.0, verbose_name='Sodium'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar',
            field=models.FloatField(default=-1.0, verbose_name='Sugar'),
        ),
    ]
