# Generated by Django 2.2.4 on 2019-08-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190812_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='monosaturated_fats',
            new_name='monounsaturated_fats',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='polysaturated_fats',
            new_name='polyunsaturated_fats',
        ),
    ]
