# Generated by Django 2.2.6 on 2019-10-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20191009_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='full_info_ru',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_ru',
        ),
        migrations.RemoveField(
            model_name='measurementunit',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='full_info_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
    ]
