# Generated by Django 2.2.6 on 2019-10-10 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20191009_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='full_info_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Full info'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.Category', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='measurementunit',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_info_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Full info'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
