# Generated by Django 2.2.6 on 2019-10-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20191010_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='full_info_de',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='full_info_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='full_info_es',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='full_info_pt',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='full_info_ru',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_pt',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name_ru',
        ),
    ]
