# Generated by Django 2.2.6 on 2019-10-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20191010_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_de',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_pt',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_ru',
        ),
    ]
