# Generated by Django 2.2.8 on 2020-01-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_products', to='users.UserProfile'),
        ),
    ]
