# Generated by Django 2.2.8 on 2020-01-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200123_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='favorite',
            new_name='favorited_by',
        ),
    ]
