# Generated by Django 2.2.8 on 2019-12-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0021_auto_20191010_0846'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayInPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True, verbose_name='Day in diet plan')),
            ],
        ),
        migrations.CreateModel(
            name='DietPlanCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Category')),
            ],
            bases=('products.category',),
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True, unique=True, verbose_name='Name')),
                ('full_info', models.TextField(blank=True, verbose_name='Full info')),
                ('image', models.ImageField(blank=True, upload_to='article_image', verbose_name='Image')),
                ('total_days', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True, verbose_name='Day in diet plan')),
                ('premium', models.BooleanField(default=True, verbose_name='Premium')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diet_plans', to='diet_plans.DietPlanCategory', verbose_name='Category')),
                ('recipes', models.ManyToManyField(blank=True, related_name='recipes', through='diet_plans.DayInPlan', to='recipes.Recipe', verbose_name='Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='dayinplan',
            name='diet_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day', to='diet_plans.DietPlan'),
        ),
        migrations.AddField(
            model_name='dayinplan',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='day', to='recipes.Recipe'),
        ),
    ]
