# Generated by Django 2.2.8 on 2020-02-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='diet_plans', through='diet_plans.DayInPlan', to='recipes.Recipe', verbose_name='Recipe'),
        ),
    ]
