# Generated by Django 2.2.8 on 2020-02-12 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet_plans', '0002_auto_20200203_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='diet_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
