# Generated by Django 2.2.5 on 2019-09-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190923_1051'),
        ('articles', '0005_auto_20190923_1021'),
    ]

    operations = [
    ]
