# Generated by Django 2.2.6 on 2019-10-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20191008_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ru',
        ),
    ]
