# Generated by Django 2.2.6 on 2019-10-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20191009_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
