# Generated by Django 2.2.6 on 2019-10-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20191010_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_es',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
