# Generated by Django 2.2.6 on 2019-10-18 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20191010_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=80, null=True, verbose_name='Last Name')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Author'),
        ),
    ]
