# Generated by Django 2.2.6 on 2019-10-18 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20191018_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_series', to='articles.ArticleSeries', verbose_name='Article Series'),
        ),
    ]
