# Generated by Django 2.2.6 on 2019-11-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20191105_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='social_url',
            field=models.URLField(blank=True, null=True, verbose_name='Social Media URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='day_in_series',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True, verbose_name='Day in Series'),
        ),
    ]
