# Generated by Django 2.2.6 on 2019-11-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20191105_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='achievement_1',
            field=models.TextField(blank=True, null=True, verbose_name='Achievement #1'),
        ),
        migrations.AddField(
            model_name='author',
            name='achievement_2',
            field=models.TextField(blank=True, null=True, verbose_name='Achievement #2'),
        ),
        migrations.AddField(
            model_name='author',
            name='achievement_3',
            field=models.TextField(blank=True, null=True, verbose_name='Achievement #3'),
        ),
    ]
