# Generated by Django 2.2.7 on 2019-11-08 07:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_article_title_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='Title color'),
        ),
    ]
