# Generated by Django 2.2.7 on 2019-11-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20191108_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, upload_to='author_photo', verbose_name='Author photo'),
        ),
    ]
