# Generated by Django 2.2.7 on 2019-11-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_author_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title_color',
        ),
    ]
