# Generated by Django 2.2.8 on 2020-02-06 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0021_remove_article_title_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseries',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='article_series', to=settings.AUTH_USER_MODEL),
        ),
    ]
