# Generated by Django 2.2.5 on 2019-09-12 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_image', verbose_name='Image')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('height', models.FloatField(verbose_name='Height')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('activity', models.CharField(choices=[('min', 'Minimal stress'), ('easy', 'Inactive'), ('ave', 'Average stress'), ('hard', 'Daily training'), ('int', 'Intensive training'), ('daily_int', 'Daily intensive training'), ('extra_hard', 'Extra hard training')], max_length=10)),
                ('goal', models.CharField(choices=[('keeping', 'Keeping fit'), ('losing', 'Losing weight'), ('ganing', 'Muscle gaininig'), ('preservation', 'Muscle reservation and fat burning')], max_length=12)),
                ('max_carbo', models.IntegerField(verbose_name='Carbohydrates')),
                ('max_fats', models.IntegerField(verbose_name='Fats')),
                ('max_calories', models.IntegerField(verbose_name='Calories')),
                ('max_proteins', models.IntegerField(verbose_name='Proteins')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
