# Generated by Django 2.2.5 on 2019-09-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='water_count',
            field=models.IntegerField(null=True, verbose_name='Water'),
        ),
    ]
