# Generated by Django 2.2.5 on 2019-09-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190916_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_calories',
            field=models.IntegerField(null=True, verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_carbo',
            field=models.IntegerField(null=True, verbose_name='Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_fats',
            field=models.IntegerField(null=True, verbose_name='Fats'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_proteins',
            field=models.IntegerField(null=True, verbose_name='Proteins'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(null=True, verbose_name='Weight'),
        ),
    ]
