# Generated by Django 2.2.5 on 2019-09-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190916_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('keeping', 'Keeping fit'), ('losing', 'Losing weight'), ('gaining', 'Muscle gaininig'), ('preservation', 'Muscle preservation and fat burning')], max_length=12),
        ),
    ]
