# Generated by Django 2.2.5 on 2019-09-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190917_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calories'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_carbo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_fats',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fats'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_proteins',
            field=models.IntegerField(blank=True, null=True, verbose_name='Proteins'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='water_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Water'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
    ]
