# Generated by Django 2.2.5 on 2019-09-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190918_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='goal',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goals',
            field=models.CharField(blank=True, choices=[('keeping', 'Keeping fit'), ('losing', 'Losing weight'), ('gaining', 'Muscle gaininig'), ('preservation', 'Muscle preservation and fat burning')], max_length=12, verbose_name='Goals'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity',
            field=models.CharField(blank=True, choices=[('min', 'Minimal stress'), ('easy', 'Inactive'), ('ave', 'Average stress'), ('hard', 'Daily training'), ('int', 'Intensive training'), ('daily_int', 'Daily intensive training'), ('extra_hard', 'Extra hard training')], max_length=10, verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
    ]
