# Generated by Django 2.2.5 on 2019-09-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_auto_20190813_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('full_info', models.TextField(blank=True, verbose_name='Full info')),
                ('image', models.ImageField(upload_to='recipe_image', verbose_name='Image')),
                ('cooking_time', models.IntegerField(blank=True, null=True, verbose_name='Cooking time')),
                ('cooking_process', models.TextField(blank=True, verbose_name='Cooking process')),
                ('portion', models.FloatField(default=100)),
                ('premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Is moderated')),
                ('products', models.ManyToManyField(blank=True, related_name='products', through='recipes.ProductAmount', to='products.Product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.AddField(
            model_name='productamount',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.Recipe'),
        ),
    ]
