# Generated by Django 2.2.8 on 2019-12-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.FloatField(default=-1.0, verbose_name='Calories'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.FloatField(default=-1.0, verbose_name='Carbohydrates'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cellulose',
            field=models.FloatField(default=-1.0, verbose_name='Cellulose'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cholesterol',
            field=models.FloatField(default=-1.0, verbose_name='Cholesterol'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fats',
            field=models.FloatField(default=-1.0, verbose_name='Fats'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='kilojoules',
            field=models.FloatField(default=-1.0, verbose_name='Kilojoules'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='monounsaturated_fats',
            field=models.FloatField(default=-1.0, verbose_name='Monosaturated fats'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='polyunsaturated_fats',
            field=models.FloatField(default=-1.0, verbose_name='Polysaturated fats'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pottasium',
            field=models.FloatField(default=-1.0, verbose_name='Pottasium'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='proteins',
            field=models.FloatField(default=-1.0, verbose_name='Proteins'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='saturated_fats',
            field=models.FloatField(default=-1.0, verbose_name='Saturated fats'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sodium',
            field=models.FloatField(default=-1.0, verbose_name='Sodium'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sugar',
            field=models.FloatField(default=-1.0, verbose_name='Sugar'),
        ),
    ]
