# Generated by Django 2.2.3 on 2019-07-12 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190709_1753'),
        ('recipes', '0002_auto_20190710_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
