# Generated by Django 2.2.8 on 2019-12-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20191212_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='monounsaturated_fats',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='polyunsaturated_fats',
        ),
        migrations.AddField(
            model_name='recipe',
            name='unsaturated_fats',
            field=models.FloatField(default=-1.0, verbose_name='Unsaturated fats'),
        ),
    ]
