# Generated by Django 2.2.8 on 2019-12-12 14:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20191212_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('shack', 'Snack'), ('dinner', 'Dinner')], max_length=28, null=True),
        ),
    ]
