# Generated by Django 2.2.3 on 2019-07-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='meal',
            new_name='ingredients',
        ),
    ]
