# Generated by Django 2.2.3 on 2019-07-12 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190709_1753'),
        ('recipes', '0005_auto_20190712_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', models.FloatField(default=100)),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredients'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
