# Generated by Django 2.2.3 on 2019-07-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20190712_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='products',
        ),
    ]
