# Generated by Django 2.2.3 on 2019-07-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190709_1753'),
        ('recipes', '0007_remove_recipe_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
