# Generated by Django 2.2.3 on 2019-07-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20190714_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Product'),
        ),
    ]
