version: '3'

services:

  db:
    image: postgres
    restart: always
    env_file:  # <-- we use the previously defined values
      - config/db/postgres_env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "sleep 2; yes | python /fiasy/src/manage.py makemigrations --merge;
             sleep 2;
             python /fiasy/src/manage.py migrate --noinput && python /fiasy/src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/fiasy/src/
    ports:
      - "8000:8000"
    depends_on:
      - db

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    ports:
      - "9200:9200"
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
