# Generated by Django 2.2.8 on 2019-12-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feedback')),
                ('feedback_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='feedbacks.FeedbackType', verbose_name='Type')),
            ],
        ),
    ]
